In [6]:
import pandas as pd

df=pd.read_csv(r'C:\Users\Sneha Srishti\Desktop\Programming for DS&AI\Employe_Performance_dataset.csv')


# Q1: Load the dataset and display the first 10 rows
print(df.head(10))

   ID                Name  Age  Gender Department  Salary Joining Date  \
0   1        Cory Escobar   48  Female         HR    5641   2015-05-03
1   2     Timothy Sanchez   25   Other      Sales    4249   2020-11-09
2   3        Chad Nichols   57   Other      Sales    3058   2019-02-12
3   4  Christine Williams   58  Female         IT    5895   2017-09-08
4   5        Amber Harris   35   Other         IT    4317   2020-02-15
5   6         Ashley Howe   29  Female         HR    2591   2016-06-24
6   7         David Olson   39  Female      Sales    6826   2023-05-11
7   8        Amanda Baker   52   Other         HR    6285   2015-04-01
8   9       Jeremy Wright   63  Female      Sales    9862   2024-02-07
9  10      Brian Faulkner   30    Male         IT    8202   2018-05-26

   Performance Score  Experience    Status     Location  Session
0                2.0          16    Active     New York    Night
1                2.0          11  Inactive  Los Angeles  Evening
2                NaN           1  Inactive     New York  Morning
3                2.0          13  Inactive  Los Angeles  Evening
4                5.0          16  Inactive     New York  Evening
5                1.0           6    Active      Chicago  Evening
6                NaN           4    Active     New York    Night
7                NaN           8  Inactive      Chicago  Evening
8                NaN           3  Inactive     New York    Night
9                1.0           9    Active  Los Angeles  Morning

In [ ]:
#Q2
print (df.dtypes)

ID                     int64
Name                  object
Age                    int64
Gender                object
Department            object
Salary                 int64
Joining Date          object
Performance Score    float64
Experience             int64
Status                object
Location              object
Session               object
dtype: object

In [ ]:
#Q3
df.shape

(1000, 12)

In [ ]:
#Q4
df[['Name','Age','Salary']]

                   Name  Age  Salary
0          Cory Escobar   48    5641
1       Timothy Sanchez   25    4249
2          Chad Nichols   57    3058
3    Christine Williams   58    5895
4          Amber Harris   35    4317
..                  ...  ...     ...
995       Pamela Reeves   49    7652
996        Todd Johnson   29    6754
997     Michael Sanchez   18    5278
998       Ashley Taylor   51    5437
999         Shawn Scott   45    7364

[1000 rows x 3 columns]

In [ ]:
#Q5
df.iloc[:5]

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
0,1,Cory Escobar,48,Female,HR,5641,2015-05-03,2.0,16,Active,New York,Night
1,2,Timothy Sanchez,25,Other,Sales,4249,2020-11-09,2.0,11,Inactive,Los Angeles,Evening
2,3,Chad Nichols,57,Other,Sales,3058,2019-02-12,NaN,1,Inactive,New York,Morning
3,4,Christine Williams,58,Female,IT,5895,2017-09-08,2.0,13,Inactive,Los Angeles,Evening
4,5,Amber Harris,35,Other,IT,4317,2020-02-15,5.0,16,Inactive,New York,Evening

In [ ]:
#Q6
sales_df = df.loc[df['Department'] == 'Sales']
sales_df.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
1,2,Timothy Sanchez,25,Other,Sales,4249,2020-11-09,2.0,11,Inactive,Los Angeles,Evening
2,3,Chad Nichols,57,Other,Sales,3058,2019-02-12,NaN,1,Inactive,New York,Morning
6,7,David Olson,39,Female,Sales,6826,2023-05-11,NaN,4,Active,New York,Night
8,9,Jeremy Wright,63,Female,Sales,9862,2024-02-07,NaN,3,Inactive,New York,Night
10,11,Nicole Bell,42,Female,Sales,5336,2015-01-28,3.0,7,Active,Los Angeles,Evening

In [ ]:
#Q7 
filtered=df.loc[(df['Salary']>8000)& (df['Status'] == 'Active')]

filtered.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
9,10,Brian Faulkner,30,Male,IT,8202,2018-05-26,1.0,9,Active,Los Angeles,Morning
24,25,Tracy Carlson,21,Male,HR,9275,2022-04-09,4.0,12,Active,New York,Morning
38,39,Jordan Scott,33,Other,Sales,8678,2016-05-15,5.0,9,Active,Los Angeles,Evening
39,40,Lisa Wagner,36,Male,HR,8870,2024-08-12,4.0,17,Active,Los Angeles,Evening
60,61,Andrew Shannon,51,Other,Sales,8544,2020-02-08,NaN,6,Active,New York,Evening

In [20]:
#Q8: >5 years and Performance Score >=4
df['Joining Date'] = pd.to_datetime(df['Joining Date'])
current_year = pd.Timestamp.now().year
df['Years_with_Company'] = current_year - df['Joining Date'].dt.year
result = df.loc[(df['Years_with_Company'] > 5) & (df['Performance Score'] >= 4)]
result.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session,Years_with_Company
4,5,Amber Harris,35,Other,IT,4317,2020-02-15,5.0,16,Inactive,New York,Evening,6
11,12,Rodney Richardson,60,Other,HR,6908,2015-03-14,4.0,19,Active,Chicago,Night,11
17,18,Jacqueline Randall,31,Female,HR,3519,2018-05-18,4.0,6,Active,New York,Morning,8
18,19,Nancy Stephens,38,Male,HR,9061,2017-07-16,5.0,16,Inactive,Chicago,Night,9
22,23,Bryce Carter,35,Female,Sales,9598,2015-12-16,4.0,4,Inactive,New York,Night,11

In [ ]:
#Q9
df.iloc[::2].head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session,Years_with_Company
0,1,Cory Escobar,48,Female,HR,5641,2015-05-03,2.0,16,Active,New York,Night,11
2,3,Chad Nichols,57,Other,Sales,3058,2019-02-12,NaN,1,Inactive,New York,Morning,7
4,5,Amber Harris,35,Other,IT,4317,2020-02-15,5.0,16,Inactive,New York,Evening,6
6,7,David Olson,39,Female,Sales,6826,2023-05-11,NaN,4,Active,New York,Night,3
8,9,Jeremy Wright,63,Female,Sales,9862,2024-02-07,NaN,3,Inactive,New York,Night,2

In [26]:
#Q10
threshold = sales_df['Salary'].quantile(0.9)
top_sales = sales_df[sales_df['Salary'] >= threshold]
top_sales.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
8,9,Jeremy Wright,63,Female,Sales,9862,2024-02-07,NaN,3,Inactive,New York,Night
22,23,Bryce Carter,35,Female,Sales,9598,2015-12-16,4.0,4,Inactive,New York,Night
29,30,Rachel Ramsey,22,Male,Sales,9661,2016-08-18,2.0,17,Inactive,Chicago,Night
215,216,Sara Jones,50,Female,Sales,9377,2019-10-16,NaN,3,Active,Los Angeles,Morning
228,229,Christie Warren,51,Female,Sales,9139,2020-08-16,5.0,1,Active,Chicago,Night